/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data;

/**
 *
 * @author User
 */

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Data extends javax.swing.JFrame {

    /**
     * Creates new form Data
     */
    
   //mengirimkan perintah ke Database
    public Statement st;
    //menyimpan hasil dari perintah select
    public ResultSet rs;
    //untuk menyambungkan ke peckage koneksi dan class koneksi
    Connection cn = Koneksi.Koneksi.getKoneksi();
    public Data() {
        initComponents();
        Tampil();
    }
   //memiliki fungsi method hapus
private void hapus(){
        TextKode.setText(" ");
        TextJenis.setText(" ");
        TextMerek.setText(" ");
        TextBerat.setText(" ");
        //ketika sudah klik hapus button save akan menampilkan save
        BSimpan.setText("Save");
    }
//memiliki fungsi untuk menampilkan select database ke table
private void Tampil(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM sepatu");
            
            DefaultTableModel model= new DefaultTableModel();
            model.addColumn("KodeSepatu");
            model.addColumn("Jenis");
            model.addColumn("Merek");
            model.addColumn("Berat");
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()){
                Object[] data = {
                    rs.getString("KodeSepatu"),
                    rs.getString("Jenis"),
                    rs.getString("Merek"),
                    rs.getString("Berat")
                    
            };
                model.addRow(data);
                TabelSepatu.setModel(model);
            }
        }catch (Exception e){
        }
    }
//memiliki fungsi untuk mencari ke database ke table sepatu colom KodeSepatu
private void Search(){
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM sepatu WHERE KodeSepatu like '%"+TextCari.getText()+"%'");
            
            DefaultTableModel model= new DefaultTableModel();
            model.addColumn("KodeSepatu");
            model.addColumn("Jenis");
            model.addColumn("Merek");
            model.addColumn("Berat");
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()){
                Object[] data = {
                    rs.getString("KodeSepatu"),
                    rs.getString("Jenis"),
                    rs.getString("Merek"),
                    rs.getString("Berat")
                    
            };
                model.addRow(data);
                TabelSepatu.setModel(model);
            }
        }catch (Exception e){
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TextKode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextJenis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextMerek = new javax.swing.JTextField();
        TextBerat = new javax.swing.JTextField();
        BSimpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelSepatu = new javax.swing.JTable();
        Search = new javax.swing.JButton();
        TextCari = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("DeVinne Txt BT", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistem Pencatatan Data Pembelian Sepatu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 30, 465, 29);

        TextKode.setBackground(new java.awt.Color(255, 255, 255));
        TextKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextKodeActionPerformed(evt);
            }
        });
        getContentPane().add(TextKode);
        TextKode.setBounds(160, 80, 287, 24);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Sepatu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 80, 72, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Sepatu");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 74, 16);

        TextJenis.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TextJenis);
        TextJenis.setBounds(160, 120, 287, 24);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Merek Sepatu");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 79, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Berat Sepatu");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 200, 74, 16);

        TextMerek.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TextMerek);
        TextMerek.setBounds(160, 160, 287, 24);

        TextBerat.setBackground(new java.awt.Color(255, 255, 255));
        TextBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBeratActionPerformed(evt);
            }
        });
        getContentPane().add(TextBerat);
        TextBerat.setBounds(160, 200, 287, 24);

        BSimpan.setText("Save");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BSimpan);
        BSimpan.setBounds(250, 270, 58, 32);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 270, 66, 32);

        TabelSepatu.setBackground(new java.awt.Color(255, 255, 255));
        TabelSepatu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KodeSepatu", "Jenis", "Merek", "Berat"
            }
        ));
        TabelSepatu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelSepatuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelSepatu);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 310, 465, 83);

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search);
        Search.setBounds(80, 410, 71, 32);

        TextCari.setBackground(new java.awt.Color(255, 255, 255));
        TextCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCariActionPerformed(evt);
            }
        });
        getContentPane().add(TextCari);
        TextCari.setBounds(160, 410, 280, 32);

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(450, 410, 51, 32);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Desain tanpa judul (1).png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 590, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_SearchActionPerformed

    private void TextCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCariActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TextCariActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            st = cn.createStatement();
            String sql = "DELETE FROM sepatu WHERE KodeSepatu = '"+TextKode.getText()+ "'";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data sudah di hapus");
            Tampil();
            hapus();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:

        try{
            //MEMILIKI FUNGSI UNTUK MENGECEK APAKAH ADA DATA YANG SAMA
            if (BSimpan.getText()=="Save"){
                String cek = "SELECT * FROM sepatu WHERE KodeSepatu = '"+ TextKode.getText()+"'";
                rs = st.executeQuery(cek);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null,"Data sudah ada");
                    //KALAU TIDAK ADA DIA AKAN MELAKNJUTKAN MEMASUKKAN DATA KE DATABASE
                }else{
                    String sql = "INSERT INTO sepatu VALUES ('"+TextKode.getText()+
                    "','" + TextJenis.getText()+
                    "','" + TextMerek.getText()+
                    "','"+ TextBerat.getText()+"')";
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"Data sudah tersimpan");
                    Tampil();
                    hapus();
                }
                //MEMILIKI FUNGSI UNTUK UPDATE DATA
            }else{
                String update = "UPDATE sepatu SET Jenis = '" + TextJenis.getText()+
                "', Merek = '" +TextMerek.getText()+
                "', Berat = '" + TextBerat.getText()+
                "' WHERE KodeSepatu ='" + TextKode.getText()+"'";
                st.executeUpdate(update);
                JOptionPane.showMessageDialog(null,"Data sudah tersimpan");
                Tampil();
                hapus();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BSimpanActionPerformed

    private void TabelSepatuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelSepatuMouseClicked
        // TODO add your handling code here:
        //
        TextKode.setText(TabelSepatu.getValueAt(TabelSepatu.getSelectedRow(), 0).toString());
        TextJenis.setText(TabelSepatu.getValueAt(TabelSepatu.getSelectedRow(), 1).toString());
        TextMerek.setText(TabelSepatu.getValueAt(TabelSepatu.getSelectedRow(), 2).toString());
        TextBerat.setText(TabelSepatu.getValueAt(TabelSepatu.getSelectedRow(), 3).toString());

        TextKode.setEditable(false);
        BSimpan.setText("Change");
    }//GEN-LAST:event_TabelSepatuMouseClicked

    private void TextKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextKodeActionPerformed

    private void TextBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBeratActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSimpan;
    private javax.swing.JButton Search;
    private javax.swing.JTable TabelSepatu;
    private javax.swing.JTextField TextBerat;
    private javax.swing.JTextField TextCari;
    private javax.swing.JTextField TextJenis;
    private javax.swing.JTextField TextKode;
    private javax.swing.JTextField TextMerek;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
